name: main page test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:114.0
        ports:
          - 4444:4444

    steps:
      - name: copy repo
        uses: actions/checkout@v3

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: install allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure-2.27.0.zip -d /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/local/bin/allure

      - name: run test
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: mvn clean test -DsuiteXmlFile=src/test/resources/testng.xml
        continue-on-error: true

      - name: generate report
        if: always()
        run: allure generate ./target/allure-results -o ./target/allure-report --clean

      - name: save allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
